### ISSUE TITLE
CognitoUser.authenticateUser throws Exception "_TypeError (type 'Null' is not a subtype of type 'String'):

### ISSUE THREAD

**Issue by methompson** [furaiev/amazon-cognito-identity-dart-2#147]
I'm using version 1.0.1
When I call authenticateUser on a CognitoUser object, I get an Exception: `_TypeError (type 'Null' is not a subtype of type 'String')`

Here's a StackTrace:
```
#0      CognitoUser._authenticateUserInternal (package:amazon_cognito_identity_dart_2/src/cognito_user.dart:78:18)
#1      CognitoUser._authenticateUserDefaultAuth (package:amazon_cognito_identity_dart_2/src/cognito_user.dart:698:12)
<asynchronous suspension>
#2      CognitoUser.authenticateUser (package:amazon_cognito_identity_dart_2/src/cognito_user.dart:478:14)
<asynchronous suspension>
#3      CognitoAuthHandler.authenticateUserWithCognito (package:app_name/shared/cognito-auth-handler.dart:36:17)
<asynchronous suspension>
#4      CognitoAuthHandler.logUserIn (package: app_name/shared/cognito-auth-handler.dart:16:19)
<asynchronous suspension>
#5      AuthModel.logUserInWithHandler (package: app_name/provider-models/auth-model.dart:189:17)
<asynchronous suspension>
#6      LoginFieldsState.logUserIn (package: app_name/ui/pages/login.dart:444:7)
<asynchronous suspension>
```

Here's the code I use:

```
final userPool = new CognitoUserPool(userPoolId, clientId);
final cognitoUser = new CognitoUser(username, userPool);
final authDetails = new AuthenticationDetails(username: username, password: password);

CognitoUserSession? session;
try {
  session = await cognitoUser.authenticateUser(authDetails);
} catch (e) {
  // Handle Errors
}
```
where userPoolId, clientId, username, userPool and password are all defined elsewhere in the application.

This code worked earlier using version 1.0.0-nullsafety.2

This issue is obviously on line 78 of cognito_user.dart:
`final String challengeName = dataAuthenticate['ChallengeName'];`

If 'ChallengeName' isn't a key in dataAuthenticate, the function will throw an exception. An earlier version defined challengeName as `String?`. Obviously the operation listed above is unsafe, and it should be reverted to

`final String? challengeName = dataAuthenticate['ChallengeName'];`

**Comment by methompson** [comment]
I've tested the code fix in this PR: https://github.com/furaiev/amazon-cognito-identity-dart-2/pull/148 and it resolves the issue I encountered.
