### ISSUE TITLE
NotAuthorizedException, message: Incorrect username or password

### ISSUE THREAD

**Issue by ctalladen78** [furaiev/amazon-cognito-identity-dart-2#157]
Hi I am getting this error when calling `CognitoUser#authenticateUser(authDetails)`
credentials are hardcoded during testing

```
Unhandled Exception: CognitoClientException{statusCode: 400, code: NotAuthorizedException, name: NotAuthorizedException, message: Incorrect username or password.}
#0      CognitoUser._authenticateUserDefaultAuth.respondToAuthChallenge (package:amazon_cognito_identity_dart/src/cognito_user.dart:581:9)
<asynchronous suspension>
#1      CognitoUser._authenticateUserDefaultAuth (package:amazon_cognito_identity_dart/src/cognito_user.dart:599:30)
<asynchronous suspension>
#2      CognitoUser.authenticateUser (package:amazon_cognito_identity_dart/src/cognito_user.dart:437:14)
```

**Comment by muhammadshahidraficp** [comment]
Any update on this issue ?
I am facing this issue during flutter web integration testing.

**Comment by furaiev** [comment]
Is this issue still topical?

**Comment by vaidehi44** [comment]
@ctalladen78 @muhammadshahidraficp did you get any solution for this? I am getting this error in my web application even in development mode.
